export const filmsData = [
  {
    id: 1,
    image: "/images/parasite.png",
    title: "Parasite",
    year: "2019",
    nation: "South Korea",
    description:
      "A darkly comedic thriller about the Kim family, who manipulate their way into the lives of the wealthy Park family. However, their scheme unravels in unexpected and shocking ways.",
    directors: "Bong Joon-ho",
    writers: "Bong Joon-ho, Han Jin-won",
    actor: "Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong",
    genres: "Comedy, Drama, Thriller",
    duration: "132 min",
    language: "Korean",
    releaseDate: "21 May 2019",
    disambiguation: "R",
    rating: 8.6,
    trailer: "https://www.youtube.com/embed/5xH0HfJHsaY",
  },
  {
    id: 2,
    image: "/images/getout.png",
    title: "Get Out",
    year: "2017",
    nation: "USA",
    description:
      "A young African American man visits his white girlfriend's family estate, where he uncovers disturbing secrets about their true intentions.",
    directors: "Jordan Peele",
    writers: "Jordan Peele",
    actor: "Daniel Kaluuya, Allison Williams, Bradley Whitford",
    genres: "Horror, Mystery, Thriller",
    duration: "104 min",
    language: "English",
    releaseDate: "24 February 2017",
    disambiguation: "R",
    rating: 7.7,
    trailer: "https://www.youtube.com/embed/sRfnevzM9kQ",
  },
  {
    id: 3,
    image: "/images/aquietplace.png",
    title: "A Quiet Place",
    year: "2018",
    nation: "USA",
    description:
      "In a post-apocalyptic world overrun by creatures that hunt by sound, a family must live in silence to survive.",
    directors: "John Krasinski",
    writers: "Bryan Woods, Scott Beck, John Krasinski",
    actor: "Emily Blunt, John Krasinski, Millicent Simmonds",
    genres: "Drama, Horror, Sci-Fi",
    duration: "90 min",
    language: "English, American Sign Language",
    releaseDate: "6 April 2018",
    disambiguation: "PG-13",
    rating: 7.5,
    trailer: "https://www.youtube.com/embed/p9wE8dyzEJE",
  },
  {
    id: 4,
    image: "/images/nomadland.png",
    title: "Nomadland",
    year: "2020",
    nation: "USA",
    description:
      "A woman in her 60s, who, after the economic collapse of a company town in rural Nevada, becomes a modern-day nomad, traveling in her van through the American West.",
    directors: "Chloé Zhao",
    writers: "Chloé Zhao",
    actor: "Frances McDormand, David Strathairn, Linda May",
    genres: "Drama",
    duration: "107 min",
    language: "English",
    releaseDate: "26 February 2021",
    disambiguation: "R",
    rating: 7.3,
    trailer: "https://www.youtube.com/embed/6sxCFZ8_d84",
  },
  {
    id: 5,
    image: "/images/lalaland.png",
    title: "La La Land",
    year: "2016",
    nation: "USA",
    description:
      "A musical about a jazz musician and an aspiring actress who meet and fall in love in Los Angeles while pursuing their dreams.",
    directors: "Damien Chazelle",
    writers: "Damien Chazelle",
    actor: "Ryan Gosling, Emma Stone, John Legend",
    genres: "Comedy, Drama, Music, Musical, Romance",
    duration: "128 min",
    language: "English",
    releaseDate: "25 December 2016",
    disambiguation: "PG-13",
    rating: 8.0,
    trailer: "https://www.youtube.com/embed/0pdqf4P9MB8",
  },
  {
    id: 6,
    image: "/images/joker.png",
    title: "Joker",
    year: "2019",
    nation: "USA",
    description:
      "A gritty character study of Arthur Fleck, a mentally unstable man who becomes the iconic villain, the Joker, in Gotham City.",
    directors: "Todd Phillips",
    writers: "Todd Phillips, Scott Silver",
    actor: "Joaquin Phoenix, Robert De Niro, Zazie Beetz",
    genres: "Crime, Drama, Thriller",
    duration: "122 min",
    language: "English",
    releaseDate: "4 October 2019",
    disambiguation: "R",
    rating: 8.4,
    trailer: "https://www.youtube.com/embed/zAGVQLHvwOY",
  },
  {
    id: 7,
    image: "/images/promisingyoungwoman.png",
    title: "Promising Young Woman",
    year: "2020",
    nation: "USA",
    description:
      "A young woman, traumatized by a tragic event, seeks vengeance against those who wronged her while pretending to lead a double life.",
    directors: "Emerald Fennell",
    writers: "Emerald Fennell",
    actor: "Carey Mulligan, Bo Burnham, Alison Brie",
    genres: "Crime, Drama, Thriller",
    duration: "113 min",
    language: "English",
    releaseDate: "25 December 2020",
    disambiguation: "R",
    rating: 7.4,
    trailer: "https://www.youtube.com/embed/7i5kiFDunk8",
  },
  {
    id: 8,
    image: "/images/minari.png",
    title: "Minari",
    year: "2020",
    nation: "USA",
    description:
      "A Korean-American family moves to a rural Arkansas farm in pursuit of their American Dream, facing both challenges and opportunities.",
    directors: "Lee Isaac Chung",
    writers: "Lee Isaac Chung",
    actor: "Steven Yeun, Yeri Han, Alan S. Kim",
    genres: "Drama",
    duration: "115 min",
    language: "Korean, English",
    releaseDate: "26 February 2021",
    disambiguation: "PG-13",
    rating: 7.6,
    trailer: "https://www.youtube.com/embed/KQ0gFidlro8",
  },
  {
    id: 9,
    image: "/images/dune.png",
    title: "Dune",
    year: "2021",
    nation: "USA",
    description:
      "In a distant future, a young noble named Paul Atreides must navigate political intrigue and a desert planet's hostile environment to secure the future of his family and people.",
    directors: "Denis Villeneuve",
    writers: "Jon Spaihts, Denis Villeneuve, Eric Roth",
    actor: "Timothée Chalamet, Zendaya, Oscar Isaac",
    genres: "Adventure, Drama, Sci-Fi",
    duration: "155 min",
    language: "English",
    releaseDate: "21 October 2021",
    disambiguation: "PG-13",
    rating: 7.3,
    trailer: "https://www.youtube.com/embed/8g18jFHCLXk",
  },
  {
    id: 10,
    image: "/images/thegreenknight.png",
    title: "The Green Knight",
    year: "2021",
    nation: "USA",
    description:
      "A reimagining of the Arthurian legend, the film follows Sir Gawain as he embarks on a quest to confront the enigmatic Green Knight.",
    directors: "David Lowery",
    writers: "David Lowery",
    actor: "Dev Patel, Alicia Vikander, Joel Edgerton",
    genres: "Adventure, Drama, Fantasy",
    duration: "130 min",
    language: "English",
    releaseDate: "30 July 2021",
    disambiguation: "R",
    rating: 6.7,
    trailer: "https://www.youtube.com/embed/VoJc2tH3WBw",
  },
];
